### ISSUE TITLE
showing reload page error even after reinstall spicetify and the visualizer in custom apps

### ISSUE THREAD

**Issue by dipto8103** [Konsl/spicetify-ncs-visualizer#10] opened 2023-10-24 08:00 UTC

**Comment by dipto8103** [comment] 2023-10-24 08:02
After updating spicetify with my new theme the visualizer was not functioning. It showed reload tab and then it never worked and stayed in that way. What should I do to make it work again?

**Comment by Konsl** [comment] 2023-10-29 21:54
duplicate of #11

**Closed by Konsl** 2023-10-29 21:54 UTC
