### ISSUE TITLE
Visual glitch (only bottom part visible)

### ISSUE THREAD

**Issue by danhangman** [Konsl/spicetify-ncs-visualizer#5] opened 2023-08-19 09:15 UTC
<img width="394" alt="image" src="https://github.com/Konsl/spicetify-ncs-visualizer/assets/142660228/26e1151f-2d61-4e7b-bdde-4c2183282007">
says this

**Comment by Konsl** [comment] 2023-08-22 20:50
Seems to be a duplicate of #1.
Please try if the solution provided there solves your problem.

**Comment by danhangman** [comment] 2023-08-23 11:02
<img width="326" alt="image" src="https://github.com/Konsl/spicetify-ncs-visualizer/assets/142660228/6c406c30-1a2c-41b8-90eb-def9249c9078">
doesnt solve it im afraid, i have gone to custom apps and made a ncs-visualiser file, copied index, manifest and style into it for context

**Comment by danhangman** [comment] 2023-08-23 11:03
nvm, ive renamed the file to visualizer with a z, it was a typo on my end. works now, thanks!

**Comment by Konsl** [comment] 2023-08-27 16:57
Are you using any custom themes? If yes, which?

**Comment by Konsl** [comment] 2024-04-30 17:41
closed due to inactivity

**Closed by Konsl** 2024-04-30 17:41 UTC
Labels: bug, help wanted
